import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class AppColors {
  final Color transparent = const Color(0x00000000);
  final Color first = const Color(0xffff6600);
  final Color secondary = const Color(0xfffb8c00);
  final Color background = const Color(0xFFf9fafb);
  final Color background2 = const Color(0xfff0f5f9);
  final Color white = const Color(0xffffffff);
  final Color black = const Color(0xff222222);
  final Color orange0p5 = const Color(0xFFFFF3E0);
  final Color orange4 = const Color(0xFFFFA726);
  final Color orange = const Color(0xFFFF9800);
  final Color orange1 = const Color(0xFFFFE0B2);
  final Color lightGrey = const Color(0xffdedede);
  final Color lightGrey2 = const Color(0xFFEEEEEE);
  final Color lightGrey3 = const Color(0xfff3f4f6);
  final Color lightGrey4 = const Color(0xfff9fafb);
  final Color faGray = const Color(0xffF2F2F2);
  final Color darkGrey = const Color(0xd1474747);
  final Color gray = const Color(0xff1f2937);
  final Color disabled = const Color(0xffe9e9e9);
  final Color lightPrimary = const Color(0xfffff7ed);
  final Color lightBackground = const Color(0xfff0f5f9);
  final Color error = const Color(0xfffe4242);
  final Color shadow = const Color(0x45000000);
  final Color textGrey = const Color(0xff4f4f4f);
  final Color grey = const Color(0xFF9E9E9E);
  final Color grey1 = const Color(0xFFf3f4f6);
  final Color grey2 = const Color(0xFFEEEEEE);
  final Color grey3 = const Color(0xFFc4c4c4);
  final Color grey4 = const Color(0xFFBDBDBD);
  final Color grey5 = const Color(0xFF6b7280);
  final Color grey6 = const Color(0xFF757575);
  final Color grey7 = const Color(0xFF616161);
  final Color grey8 = const Color(0xFF424242);
  final Color grey8p5 = const Color(0xFF303030);
  final Color grey9 = const Color(0xFF212121);
  final Color disabledText = const Color(0xff6f6f6f);
  final Color red50 = const Color(0xFFFFEBEE);
  final Color red = const Color(0xFFF44336);
  final Color opacityRed = const Color(0xFFBA0A0A);
  final Color opacityFiol = const Color(0xFFA000D8);
  final Color lightRed = const Color(0xfffef2f2);
  final Color opacityGreen = const Color(0xFF2DB56D);
  final Color green1 = const Color(0xFFC8E6C9);
  final Color priceGreen = const Color(0xFF219653);
  final Color greenTeal = const Color(0xff10b981);
  final Color darkGreen = const Color(0xff059669);
  final Color blue = const Color(0xff00a3ff);
  final Color blue1 = const Color(0xFFBBDEFB);
  final Color queueLightBlue = const Color(0xFFe4eefc);
  final Color dashboardTextLabel = const Color(0xFF505050);
  final Color grayishDarkBlue = const Color(0xff29304d);
  final Color primary = const Color(0xFF1CAE81);
  final Color opacityIndigo = const Color(0xFF2D6CB5);
  final Color indigo9 = const Color(0xff1A237E);
  final Color indigo0p5 = const Color(0xFFE8EAF6);
  final Color indigo1 = const Color(0xFFC5CAE9);
  final Color yellow = const Color(0xffffaa00);
  final Color opacityYellow = const Color(0xFFFFA800);
  final Color violet = const Color(0xff673ab7);

  const AppColors();
}
